name: tekartik_platform_io
description: Platform io
version: 0.1.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.63 <3.0.0'

dependencies:
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
      ref: dart2

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  tekartik_platform_test:
    path: ../platform_test
  build_runner: any
  build_test: any
dependency_overrides:
  tekartik_platform:
    path: ../platform