language: dart

sudo: required
addons:
  chrome: stable

before_install:
  - nvm install node
  - node --version

dart:
  - stable
  - beta
  - dev

script:
  - cd repo_support
  - dart ./tool/travis.dart

# Only building master means that we don't run two builds for each pull request.
# branches:
#  only:
#    - master
#    - dart2

cache:
  directories:
    - $HOME/.pub-cache