name: tekartik_platform_repo
description: Platform repo (tools)
version: 0.2.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.6.5+1'
  # test dependencies without version
  tekartik_platform_io:
    git:
      url: git://github.com/tekartik/platform.dart
      ref: dart2
      path: platform_io
  tekartik_platform_browser:
    git:
      url: git://github.com/tekartik/platform.dart
      ref: dart2
      path: platform_browser
  tekartik_platform_node:
    git:
      url: git://github.com/tekartik/platform.dart
      ref: dart2
      path: platform_node
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      ref: dart2
      path: platform


