name: tekartik_platform_node
description: Platform node
version: 0.2.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
      ref: dart2
    version: '>=0.2.0'
  node_io: '>=1.0.1+2'
  path: '>=1.6.1'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  tekartik_platform_test:
    path: ../platform_test
  build_runner: '>=1.7.0'
  build_test: '>=0.10.8'
  build_node_compilers: ">=0.2.2"
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_platform:
    path: ../platform