name: tekartik_platform
version: 0.1.0
description: Get the global platform context
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'

dependencies:
  pub_semver: '>=1.4.1'
  collection: '>=1.14.10'

dev_dependencies:
  test: any
  dev_test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  build_runner: ">=0.8.8"
  build_test: ">=0.10.2"
  build_web_compilers: '>=0.4.0'