name: tekartik_platform
version: 0.1.0
description: Get the global platform context
environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  pub_semver: any
  collection: any

dev_dependencies:
  test: any
  dev_test: any
  browser: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
