name: tekartik_platform_test
description: Platform test
version: 0.1.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform

dev_dependencies:
  test: ">=0.12.34"
  dev_test: any

dependency_overrides:
  tekartik_platform:
    path: ../platform