name: tekartik_platform_test
description: Platform test
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
      ref: dart2
  build_runner: ">=0.8.8"
  build_test: ">=0.10.2"
  test: ">=1.2.0"
  dev_test: any

dev_dependencies:
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_platform:
    path: ../platform