name: tekartik_platform_browser
version: 0.1.0
description: Get the global platform context
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'

dependencies:
  pub_semver: any
  collection: any
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
      ref: dart2

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  tekartik_platform_test:
    path: ../platform_test
  build_runner: ">=0.8.8"
  build_test: ">=0.10.2"
  build_web_compilers: '>=0.4.0'

dependency_overrides:
  tekartik_platform:
    path: ../platform


